index.html
main.js
style.css

Added scripts to create section anchors that will give out the link to specific anchors.

Section Anchors

---

index.html
main.js
style.css

Made section IDs more descriptive for the linkages. Updated nav linkages.
Made some parts of the documentations clearer (You can undo these if you want to, I don't really care)
Did some CSS fixings. Added run functions onload so functions won't be messed everyhwere

Section Linkages

---

index.html

Update for version 3.4.0
Closes #XXXXX

Update for version 3.4.0 changes

---

index.html

Update the documentation to reflect the current version.
Closes #XXXXX

Update for version 4.0.0

---

index.html

Update docs to version 4.3.1
Closes #XXXXX

Update to V 4.3.1

---

index.html

Update the documentation to reflect the current state of the bot.
Closes #XXXXX

Update docs to 4.6.0

---

index.html

Update the docs to reflect bot version 4.8.1
Closes #XXXXX

Update docs to V 4.8.1

---

index.html

Update the documentation to version 4.8.5
Closes #XXXXX

Update docs to V 4.8.5

---

index.html

Update documentation to bot version `4.11.0`
Closes #XXXXX

Update to version 4.11.0

---

index.html

- Changed the guides from `config.json` to the `config` command.
- Added `invite` and `optout` commands to the list.
- Added a commands guide.
I'm not a native English speaker, if I have some orthographic mistakes I sorry for that, I'm trying to improve my English level.
Closes #12

[Feature] Added new documentation of the bot refactor

---

index.html

Added sus command to the docs.
No. Just updating the docs to the most recent version for the bot.
Closes #XXXXX

Add sus command to docs

---

index.html

This adds the `contributors` command to the documentation.
Closes #23

Add contrib command

---

index.html

Updates the description of the `config` section to explain the permissions needed to change server settings.
Closes #25

Update config command

---

index.html
main.js

Updates the docs to v. 6.0.0
Removes the <code>`</code> parser to address some display errors.
Closes #27 and #28

Refactor design a bit, update to newest version

---

index.html
style.css

Tweaks some styling, adds the privacy policy, documents the `OWNER_ID` config.
Closes #30 
Closes #32

Update to version 6.2.1

---

index.html
style.css

Adds details for the `config` changes to allow levels and thanks to be togglable. Moves version number to the sidebar.
Closes #XXXXX

Update to v 6.5.2

---

index.html

Updates the `leave` command and documents the `list` command.
Closes #41

Add list command, update leave

---

index.html

Documents the new config option for custom welcome messages.
Closes #43

Update to 6.6.3

---

index.html

Handles the updates requested in the linked issues below.
* Documents the pig latin command
* Documents the block command
* Documents the `OWNER_ID` restriction on the block, leave, and config commands
* Documents the deprecation of the purge command
* Documents the change in the user command.
Closes #45 
Closes #46 
Closes #47 
Closes #48

Update to 6.10.0

---

index.html

Removes commands' multiple names
Closes #61

Update to version 6.11.0

---

index.html

Updates the `config` documentation to reflect the new structure.
Closes #65

Update to 7.0.0

---

index.html

Updates `config` documentation.
Closes #XXXXX

Update to 7.0.2

---

index.html

Documents the change in default prefix and usage tracking.
Closes #XXXXX

Update to 7.0.5

---

index.html

Update to 7.0.8

---

index.html

Updates to version 7.1.0
Closes #XXXXX

Update to 7.1.0

---

.github/ISSUE_TEMPLATE/update.md
src/app/art-contribs/art-contribs.component.html
src/app/auto-command/auto-command.component.html
src/app/bot-config/bot-config.component.html
src/app/bot-deploy/bot-deploy.component.html
src/app/bot-setup/bot-setup.component.html
src/app/contribute/contribute.component.html
src/app/local-instance/local-instance.component.html
src/app/nav/nav.component.html
src/app/new-command/new-command.component.html
src/app/privacy/privacy.component.html
src/app/trouble/trouble.component.html
src/app/welcome/welcome.component.html
src/assets/data/automatic.ts
src/assets/data/config.ts
src/assets/data/env.ts
src/assets/data/manual.ts

Naming stuff

---

package.json
src/assets/data/manual.ts

Documents the new Becca command.
Closes #91

update: Document Becca command

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/biography/biography.component.html
src/app/biography/biography.component.spec.ts
src/app/biography/biography.component.ts
src/app/nav/nav.component.html
src/assets/data/bio.ts

Adds a more expanded biography for Becca.
Closes #XXXXX

feat: Write biography for Becca

---

package.json
src/assets/data/automatic.ts
src/assets/data/env.ts

Documents the custom emote `.env` values and
the change to the hearts listener.
Closes #XXXXX

update: Verison 9.0.0

---

package-lock.json
package.json
src/assets/data/artList.ts

Adds names for the art provided by Whisperdawn. Names were discussed
in Discord.
Closes #XXXXX

feat: art names

---

.github/workflows/deploy.yml
angular.json
package-lock.json
package.json

Updates angular-cli-ghpages to fix broken config, adds deploy CI.
Closes #XXXXX

tools: add deploy pipeline

---

.github/workflows/node.yml
CONTRIBUTING.md
karma.conf.js
package.json
src/app/app.component.spec.ts
src/app/art-contribs/art-contribs.component.spec.ts
src/app/art/art.component.html
src/app/art/art.component.spec.ts
src/app/auto-command/auto-command.component.html
src/app/auto-command/auto-command.component.spec.ts
src/app/biography/biography.component.spec.ts
src/app/bot-config/bot-config.component.html
src/app/bot-config/bot-config.component.spec.ts
src/app/bot-deploy/bot-deploy.component.spec.ts
src/app/bot-setup/bot-setup.component.html
src/app/bot-setup/bot-setup.component.spec.ts
src/app/contribute/contribute.component.spec.ts
src/app/dep-command/dep-command.component.html
src/app/dep-command/dep-command.component.spec.ts
src/app/local-instance/local-instance.component.spec.ts
src/app/man-command/man-command.component.html
src/app/man-command/man-command.component.spec.ts
src/app/nav/nav.component.html
src/app/nav/nav.component.spec.ts
src/app/new-command/new-command.component.html
src/app/new-command/new-command.component.spec.ts
src/app/privacy/privacy.component.spec.ts
src/app/trouble/trouble.component.spec.ts
src/app/welcome/welcome.component.spec.ts
src/assets/data/manual-commands/serverCommands.ts

Builds out tests for the components, enables the test step in the CI,
adds brief information to contributing documentation.
Closes #XXXXX

tools: build out tests

---

.github/dependabot.yml
.github/workflows/node.yml

Enables the dependabot CRON job.
Closes #XXXXX

tools: enable dependabot

---

src/app/art/art.component.html
src/app/art/art.component.spec.ts
src/app/art/art.component.ts
src/assets/data/artList.ts

Split the art list into comissioned works and generated works.
Splits the art list into two separate sections.
Closes #XXXXX

feat: split art list

---

package-lock.json
package.json

Update somewhere in the dependency tree broke the lint step. Adds
missing package.
Closes #XXXXX

tools: add missing package

---

package-lock.json
package.json
src/assets/data/deprecated.ts
src/assets/data/env.ts
src/assets/data/manual-commands/serverCommands.ts

- Document the new `.env` values for database encryption
- Document the deprecation of the `usage` command
Closes #161
Closes #163

feat: updates

---

README.md
angular.json
src/index.html

Update the DNS for the new domain!
Closes #XXXXX

fix: update DNS

---

.github/workflows/codeql.yml
.github/workflows/node.yml
package.json

tools: new codeql

---

package-lock.json
package.json
src/app/local-instance/local-instance.component.html
src/app/new-command/new-command.component.html
src/assets/data/config.ts
src/assets/data/env.ts
src/assets/data/manual-commands/generalCommands.ts
src/assets/data/manual-commands/serverCommands.ts

Covers multiple bot updates - see linked issue and commit history for details.
Closes #174 
Closes #175 
Closes #208

update: apply latest information

---

package-lock.json
package.json
src/app/app.module.ts
src/main.ts

Implement sentry logging.
Closes #244

feat: implement sentry

---

package-lock.json
package.json
src/assets/data/manual-commands/serverCommands.ts

Document the tweak in the role command.
Closes #XXXXX

update: 12.3.3

---

package-lock.json
package.json
src/assets/data/manual-commands/generalCommands.ts

Document the new `orbit` command.
Closes #387

feat: document orbit command

---

package-lock.json
package.json
src/assets/data/manual-commands/serverCommands.ts

Document the addition of the resetstar command.
Closes #XXXXX

feat: document resetstar

---

package-lock.json
package.json
src/assets/data/manual-commands/generalCommands.ts

- Document the new `colour` command.
Closes #410

feat: update to 12.6.0

---

package-lock.json
package.json
src/assets/data/manual-commands/serverCommands.ts

Document the new `suggestion` command.
Closes #443

feat: add suggestions

---

docs/_navbar.md
docs/manual-commands.md
docs/set-permissions.md
package-lock.json
package.json

Adds a page that briefly describes Discord's permissions system.
Closes #525

feat: document permissions

---

docs/configure-server.md
package-lock.json
package.json

Document the new configuration options for detecting links.
Closes #XXXXX

feat: link automoderation

---

docs/setup-code.md
package-lock.json
package.json

Update the env values to reflect the latest changes.
Closes #XXXXX

feat: env changes

---

docs/configure-server.md
docs/deprecated-features.md
docs/manual-commands.md
docs/setup-code.md
package-lock.json
package.json

I believe this should cover everything in the migration.
Closes #XXXXX

feat: slash migration

---

docs/_navbar.md
docs/context-commands.md
docs/manual-commands.md
package-lock.json
package.json

- Document the new currency commands: `21` and `slots`.
- Document the `bookmark` context command.
Closes #XXXXX

feat: 16.10.0

---

docs/automatic-commands.md
docs/context-commands.md
docs/manual-commands.md
docs/privacy-policy.md
package-lock.json
package.json

- Update Privacy Policy
- Add new `purge` command
- Add missing `nhcarrigan` commands
- Document activity command and listener
- Add `guess` command
Closes #XXXXX

feat: 16.12.1

---

docs/_navbar.md
docs/changelog.md
docs/privacy-policy.md
package-lock.json
package.json

- Adds a changelog page to track changes across each version
- Updates the privacy policy for the new data collected for the dashboard.
Closes #XXXXX

feat: changelog

---

docs/changelog.md
docs/manual-commands.md
package-lock.json
package.json

- Document `update` command and release schedule
Closes #XXXXX

feat: 16.9.0

---

docs/changelog.md
package-lock.json
package.json

release: 16.20.0

---

docs/index.html

feat: widgetbot

---

docs/_navbar.md
docs/changelog.md
docs/contribute.md
docs/creating-pr.md
docs/file-structure.md
docs/how-to-contribute.md
docs/index.html
docs/index.md
docs/misc.md
docs/use.md
package-lock.json
package.json

Restructures the documentation, adds clearer instruction for contributing.
Closes #XXXXX

refactor: restructure documentation

---

docs/changelog.md
docs/create-local.md
docs/setup-code.md
package-lock.json
package.json

- Add some extra details with regard to getting the necessary environment variables
- Update the changelog for 16.20.2
Closes #XXXXX

feat: clarify env, update changelog

---

docs/create-local.md
docs/deploy-code.md
docs/setup-code.md

Clarify some pain points in the contributing process.
Closes #XXXXX

chore: contributing clarifications

---

.github/workflows/md-lint.yml
.markdownlint.json

Adds a markdown lint config file, disables the line length rule. Then sets up CI to run the lint.
Closes #XXXXX

chore(tools): linting workflow

---

docs/setup-code.md

Marked `OWNER_ID` as `Required` in the setup-code.md steps.
Closes #558

Changed OWNER_ID key to Required

---

docs/_navbar.md
docs/developer-certificate.md

Documentation change that fixes #560 
Added a Developer Certificate and created a new markdown file for the same.
Closes #560

Create developer-certificate.md, fixed issue #560 for Hacktoberfest

---

docs/automatic-commands.md
docs/changelog.md
docs/manual-commands.md
docs/privacy-policy.md
docs/setup-code.md
package-lock.json
package.json

Documents the changes since the latest release.
Closes #XXXXX

docs: 17.2.0

---

docs/changelog.md
package-lock.json
package.json

docs: v17.4.1

---

docs/changelog.md
package-lock.json
package.json

release: v17.4.2

---

docs/changelog.md
package-lock.json
package.json

docs: v17.5.0

---

docs/create-local.md

Adds GitHub SignUp link to the documentation in 'Create A Local Instance' page.

Added GitHub Signup link

---

docs/changelog.md
docs/manual-commands.md
package-lock.json
package.json

docs: v17.7.0

---

docs/set-permissions.md

feat: document moderate_members permission

---

docs/changelog.md
docs/deprecated-features.md
package-lock.json
package.json

docs: v17.9.0

---

docs/index.md

feat: add twitter link

---

docs/_navbar.md
docs/terms-of-service.md

Adds a basic ToS document.
Closes #601

docs: add terms of service

---

docs/automatic-commands.md
docs/changelog.md
docs/manual-commands.md
package-lock.json
package.json

docs: v17.10.0

---

docs/_navbar.md
docs/changelog.md
docs/manual-commands.md
docs/translation.md
package-lock.json
package.json

release: v18.0.0

---

docs/_navbar.md
docs/changelog.md
docs/configure-server.md
docs/contribute.md
docs/manual-commands.md
docs/owner-commands.md
docs/use.md

docs: v18.3.0

---

docs/index.html

Move from Google Analytics to Fathom to protect user privacy.
Closes #XXXXX

feat: migrate analytics

---

docs/index.html
package-lock.json
package.json

chore: sentry releases

---

README.md
docs/_navbar.md
docs/creating-pr.md
docs/privacy-policy.md
docs/terms-of-service.md

feat: add utms

---

docs/changelog.md
docs/owner-commands.md
package-lock.json
package.json

docs: v18.4.0

---

docs/_navbar.md
docs/changelog.md
docs/manual-commands.md
docs/user-config.md
package-lock.json
package.json

docs: v18.5.1

---

docs/manual-commands.md

Updates docs with quote command

---

docs/changelog.md
package-lock.json
package.json

docs: v19.0.0

---

docs/changelog.md
docs/manual-commands.md
package-lock.json
package.json

docs: v19.0.1

---

docs/_navbar.md

Signed-off-by: takanome_dev <takanomedev221@gmail.com>
Update the date of copyright.
Closes #619

docs: update copyright date

---

docs/changelog.md
package-lock.json
package.json

docs: v19.1.0

---

docs/changelog.md
docs/configure-server.md
docs/deploy-code.md
docs/deprecated-features.md
docs/manual-commands.md
docs/privacy-policy.md
docs/setup-code.md
docs/user-config.md
package-lock.json
package.json

docs: v20.0.1

---

docs/changelog.md
docs/manual-commands.md
docs/privacy-policy.md
package-lock.json
package.json

release: v20.2.0

---

docs/changelog.md
package-lock.json
package.json

release: v20.2.1

---

docs/configure-server.md

This PR updates the server configuration documents with the links and automod subcommand group for automod commands, which were added in https://github.com/BeccaLyria/discord-bot/pull/1452
Closes #XXXXX

docs: automod links and profanity commands.

---

docs/changelog.md
docs/configure-server.md
package-lock.json
package.json

release: v21.0.1

---

docs/changelog.md
docs/manual-commands.md
package-lock.json
package.json

release: v21.1.0

---

docs/changelog.md
docs/privacy-policy.md
docs/set-permissions.md
package-lock.json
package.json

release: v21.2.0

---

docs/changelog.md
package-lock.json
package.json

release: v21.2.1

---

docs/index.md

chore: replace twitter link with mastodon

---

docs/changelog.md
package-lock.json
package.json

release: v21.4.0

---

docs/_navbar.md
docs/changelog.md
docs/create-local.md
docs/database.md
docs/deprecated-features.md
docs/index.html
docs/privacy-policy.md
docs/setup-code.md
package-lock.json
package.json

release: v22.0.0

---

docs/_navbar.md
docs/changelog.md
docs/configure-server.md
docs/manual-commands.md
docs/set-permissions.md
docs/setup-code.md
docs/use.md
package-lock.json
package.json

release: v22.1.0

---

docs/_navbar.md
docs/create-local.md
docs/creating-pr.md
docs/deploy-code.md
docs/testing-changes.md

docs: change to pnpm, document testing locally

---

docs/changelog.md
docs/manual-commands.md
package-lock.json
package.json

release: v22.2.0

---

docs/changelog.md
docs/manual-commands.md
package-lock.json
package.json

release: v22.3.0

---

docs/changelog.md
package-lock.json
package.json

release: v22.4.0

---

docs/_navbar.md
docs/set-permissions.md
docs/testing-changes.md

chore: update chat link

---

.github/workflows/md-lint.yml
package.json

chore: move to node 20

---

docs/changelog.md
docs/manual-commands.md
package-lock.json
package.json

release: v22.5.0

---

docs/manual-commands.md

Document the `/support data-request` command listed in PR [#1886](https://github.com/nhcarrigan/becca-lyria/pull/1886).
N/A

Document Data-Request Support Command

---

docs/changelog.md
docs/index.html
docs/manual-commands.md
package-lock.json
package.json

release: v23.0.0

---

docs/privacy-policy.md

feat: add warning about errors
